n = input('Qual o seu nome? ')
print('Prazer em te conhecer, {:20}!'.format(n))
print('Prazer em te conhecer, {:>20}!'.format(n))
print('Prazer em te conhecer, {:<20}!'.format(n))
print('Prazer em te conhecer, {:^20}!'.format(n))
print('Prazer em te conhecer, {:=^20}!'.format(n))
print('Prazer em te conhecer, {:❤^20}!'.format(n))
