frase = 'Curso em Vídeo Python'
print(frase)
print(len(frase))
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.lower().find('Video'))
print('Curso' in frase)
